// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveWithJoystick.h"
#include "Commands/Lights.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	cCI = new Joystick(4);
	
	bluLight = new JoystickButton(cCI, 3);
	bluLight->WhenPressed(new Lights());
	whtLight = new JoystickButton(cCI, 2);
	whtLight->WhenPressed(new Lights());
	redLight = new JoystickButton(cCI, 1);
	redLight->WhenPressed(new Lights());
	elbowStick = new Joystick(3);
	
	shoulderStick = new Joystick(2);
	
	driver = new Joystick(1);
	
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
	SmartDashboard::PutData("Lights", new Lights());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	
	// create public references to private objects created by RobotBuilder:
	redButton = redLight;
	whtButton = whtLight;
	bluButton = bluLight;
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getCCI() {
	return cCI;
}
Joystick* OI::getElbowStick() {
	return elbowStick;
}
Joystick* OI::getShoulderStick() {
	return shoulderStick;
}
Joystick* OI::getDriver() {
	return driver;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
