// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Lights.h"
Lights::Lights() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::towerLights);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void Lights::Initialize() {
	redLight = false;
	whtLight = false;
	bluLight = false;
}
// Called repeatedly when this Command is scheduled to run
void Lights::Execute() {
	// get button values
	redLight = Robot::oi->redButton->Get();
	whtLight = Robot::oi->whtButton->Get();
	bluLight = Robot::oi->bluButton->Get();
	
	// convert button values to relay value (bool to Robot::Value)
	Relay::Value red = (redLight)? (Relay::kOn) : (Relay::kOff);
	Relay::Value wht = (whtLight)? (Relay::kOn) : (Relay::kOff);
	Relay::Value blu = (bluLight)? (Relay::kOn) : (Relay::kOff);
	
	// send control values to the relays
	RobotMap::towerLightsRed->Set(red);
	RobotMap::towerLightsWht->Set(wht);
	RobotMap::towerLightsBlu->Set(blu);
}
// Make this return true when this Command no longer needs to run execute()
bool Lights::IsFinished() {
	return false;
}
// Called once after isFinished returns true
void Lights::End() {
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Lights::Interrupted() {
}
