// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Lights.h"
Lights::Lights() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::towerLights);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void Lights::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void Lights::Execute() {
	// relay output values; default is Off
	Relay::Value red = Relay::kOff;
	Relay::Value wht = Relay::kOff;
	Relay::Value blu = Relay::kOff;

	// get button values
	bool redButton = Robot::oi->redButton->Get();
	bool whtButton = Robot::oi->whtButton->Get();
	bool bluButton = Robot::oi->bluButton->Get();

	// get relay values
	bool redLight = (RobotMap::towerLightsRed->Get() != Relay::kOff);
	bool whtLight = (RobotMap::towerLightsWht->Get() != Relay::kOff);
	bool bluLight = (RobotMap::towerLightsBlu->Get() != Relay::kOff);
	
	// get relay values: if the button is pressed, invert the relay value
	if (redButton) {
		red = (redLight)? (Relay::kOff) : (Relay::kOn);
	}
	if (whtButton) {
		wht = (whtLight)? (Relay::kOff) : (Relay::kOn);
	}
	if (bluButton) {
		blu = (bluLight)? (Relay::kOff) : (Relay::kOn);
	}
	
	// send control values to the relays
	RobotMap::towerLightsRed->Set(red);
	RobotMap::towerLightsWht->Set(wht);
	RobotMap::towerLightsBlu->Set(blu);
}

// Make this return true when this Command no longer needs to run execute()
bool Lights::IsFinished() {
	// run Execute() once, then done
	return true;
}

// Called once after isFinished returns true
void Lights::End() {
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Lights::Interrupted() {
}
